### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Blip259** [ernestum/VSync-for-Processing#1]
Hi, 
I'm having some issues installing this library. 
(1) It doesn't show up on the librarys search.
(2) So instead tried to "manually install": I've placed the extracted zip in the processing library folder and restarted Processing but still doesn't seem to install . 

Any tips?

Cheers.

**Comment by ernestum** [comment]
Hi @Blip259,
thank you for your bug report. 
VSync has been developed for Processing 2.1.1  and the current version is 3.5.4. Therefore it unfortunately does not show up in the library manager any more. I probably just have to update the properties file.
However I was able to install it on my computer using the manual code. What version of processing and what operating system were you using? Did you verify that you placed the library in such a way, that `sketchbook/libraries/VSync/` contains the file `library.properties` and the folders `examples`, `library`, `reference` and `src`?

**Comment by ernestum** [comment]
Turns out there was an issue since I changed my github handle. Shoutout to @prisonerjohn who [updated the URL](https://github.com/processing/processing-docs/commit/e146a5b77b759e8fc89361eedfc3a875db895f2b) really fast! It should work again now:
![image](https://user-images.githubusercontent.com/1250234/117617806-5b861e80-b16d-11eb-8289-0c53cfdb973d.png)
